# Generated by Django 4.1.7 on 2023-07-05 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=20, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('onay', models.FileField(default='', upload_to='docentonay/')),
                ('özgeçmiş', models.FileField(default='', upload_to='docentCV/')),
                ('AYOK2', models.FileField(default='', upload_to='docentAYOK2/')),
                ('form5', models.FileField(default='', upload_to='profform5/', verbose_name='FORM-5')),
                ('form6', models.FileField(default='', upload_to='profform6/', verbose_name='FORM-6')),
                ('tez', models.FileField(default='', upload_to='docenttezler/')),
                ('form7', models.FileField(default='', upload_to='docentform7/', verbose_name='FORM-7')),
                ('yds', models.FileField(default='', upload_to='docentyds_belge/', verbose_name='YDS Sonuç Belgesi')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yükleme Tarihi')),
            ],
        ),
    ]
