# Generated by Django 4.1.7 on 2023-07-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='özgeçmiş',
        ),
        migrations.AddField(
            model_name='prof',
            name='ozgecmis',
            field=models.FileField(default='', upload_to='docentCV/', verbose_name='Özgeçmiş'),
        ),
    ]
