# Generated by Django 4.1.7 on 2023-07-05 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_remove_document_title_document_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yükleme Tarihi'),
        ),
    ]
