# Generated by Django 4.1.7 on 2023-07-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_document_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='yayinadi',
            field=models.CharField(choices=[('Makale', 'Makale'), ('Tez', 'Tez'), ('Kitap', 'Kitap'), ('Bildiri', 'Bildiri'), ('Patent', 'Patent'), ('Rapor', 'Rapor'), ('Editörlük', 'Editörlük'), ('Teknik notlar', 'Teknik notlar'), ('Araştırma mektupları', 'Araştırma mektupları'), ('Derleme makaleleri', 'Derleme makaleleri')], default='Makale', max_length=100, verbose_name='Yayın Adı'),
        ),
    ]
