# Generated by Django 4.1.7 on 2023-07-05 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yardimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=20, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('onay', models.FileField(default='', upload_to='onay/', verbose_name='Onaylı Doçentlik Belgesi')),
                ('özgeçmiş', models.FileField(default='', upload_to='CV/', verbose_name='Özgeçmiş')),
                ('AYOK', models.FileField(default='', upload_to='AYOK/', verbose_name='AYÖK belgesi')),
                ('tez', models.FileField(default='', upload_to='tezler/', verbose_name='Tez')),
                ('yds', models.FileField(default='', upload_to='yd_belge/', verbose_name='Yabancı Dil Sınav Sonuç Belgesi')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yükleme Tarihi')),
            ],
        ),
    ]
