# Generated by Django 4.1.7 on 2023-07-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yardimci',
            old_name='özgeçmiş',
            new_name='ozgecmis',
        ),
    ]
