# Generated by Django 4.1.7 on 2023-07-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_M1_1', models.CharField(blank=True, choices=[('60/30', '60/30')], max_length=20, null=True, verbose_name='M1-1')),
                ('kategori_M2_1', models.CharField(blank=True, choices=[('50/25', '50/25')], max_length=20, null=True, verbose_name='M2-1')),
                ('kategori_M3_1', models.CharField(blank=True, choices=[('40/20', '40/20')], max_length=20, null=True, verbose_name='M3-1')),
                ('kategori_M4_1', models.CharField(blank=True, choices=[('15/8', '15/8')], max_length=20, null=True, verbose_name='M4-1')),
                ('kategori_M5_1', models.CharField(blank=True, choices=[('30/15', '30/15')], max_length=20, null=True, verbose_name='M5-1')),
                ('kategori_M6_1', models.CharField(blank=True, choices=[('15/5', '15/5')], max_length=20, null=True, verbose_name='M6-1')),
                ('kategori_M7_1', models.CharField(blank=True, choices=[('30/15', '30/15')], max_length=20, null=True, verbose_name='M7-1')),
                ('kategori_M8_1', models.CharField(blank=True, choices=[('20/10', '20/10')], max_length=20, null=True, verbose_name='M8-1')),
                ('kategori_N1-Kamu ve/veya özel sektörde, Teknoparklarda ve/veya sanayi kuruluşlarının Ar-ge birimlerinde en az 3 ay süreli danışmanlık hizmeti ve eğiticilik (x ay)_1', models.CharField(blank=True, choices=[('2', '2')], max_length=20, null=True, verbose_name='N1-Kamu ve/veya özel sektörde, Teknoparklarda ve/veya sanayi kuruluşlarının Ar-ge birimlerinde en az 3 ay süreli danışmanlık hizmeti ve eğiticilik (x ay)-1')),
                ('kategori_N2-Teknopark ve benzeri alanlarda şirket kurucusu/ortağı olmak ve şirket faaliyetlerine devam ediyor olmak _1', models.CharField(blank=True, choices=[('20', '20')], max_length=20, null=True, verbose_name='N2-Teknopark ve benzeri alanlarda şirket kurucusu/ortağı olmak ve şirket faaliyetlerine devam ediyor olmak -1')),
                ('kategori_N3-Üniversite – Sanayi / Kamu Kurumları işbirliği kapsamında tamamlanmış proje tasarım faaliyetleri_1', models.CharField(blank=True, choices=[('5', '5')], max_length=20, null=True, verbose_name='N3-Üniversite – Sanayi / Kamu Kurumları işbirliği kapsamında tamamlanmış proje tasarım faaliyetleri-1')),
                ('kategori_N4-Bilirkişilik faaliyeti (x adet) _1', models.CharField(blank=True, choices=[('2', '2')], max_length=20, null=True, verbose_name='N4-Bilirkişilik faaliyeti (x adet) -1')),
                ('kategori_O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)_1', models.CharField(blank=True, choices=[('5', '5')], max_length=20, null=True, verbose_name='O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)-1')),
                ('kategori_O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)_2', models.CharField(blank=True, choices=[('2', '2')], max_length=20, null=True, verbose_name='O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)-2')),
                ('kategori_O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)_3', models.CharField(blank=True, choices=[('5', '5')], max_length=20, null=True, verbose_name='O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)-3')),
                ('kategori_O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)_4', models.CharField(blank=True, choices=[('15', '15')], max_length=20, null=True, verbose_name='O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)-4')),
                ('kategori_O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)_5', models.CharField(blank=True, choices=[('1', '1')], max_length=20, null=True, verbose_name='O1-Q kategorisindeki dergilerde yapılan hakemlik (her hakemlik başına)-5')),
                ('kategori_O2-Q kategorisindeki ve dışındaki dergilerde yayın kurulu üyelikleri (x yıl)_1', models.CharField(blank=True, choices=[('3', '3')], max_length=20, null=True, verbose_name='O2-Q kategorisindeki ve dışındaki dergilerde yayın kurulu üyelikleri (x yıl)-1')),
                ('kategori_O2-Q kategorisindeki ve dışındaki dergilerde yayın kurulu üyelikleri (x yıl)_2', models.CharField(blank=True, choices=[('1', '1')], max_length=20, null=True, verbose_name='O2-Q kategorisindeki ve dışındaki dergilerde yayın kurulu üyelikleri (x yıl)-2')),
                ('kategori_O3-Bilim - Sanat kurulu başkanlığı / üyeliği (x yıl)_1', models.CharField(blank=True, choices=[('5/4', '5/4')], max_length=20, null=True, verbose_name='O3-Bilim - Sanat kurulu başkanlığı / üyeliği (x yıl)-1')),
                ('kategori_O4-Uluslararası bir standartın hazırlanmasında görev almak_1', models.CharField(blank=True, choices=[('20', '20')], max_length=20, null=True, verbose_name='O4-Uluslararası bir standartın hazırlanmasında görev almak-1')),
                ('kategori_O5-Bilimsel / Sanatsal toplantı düzenleme kurul başkanlığı / editörlüğü / kurul üyeliğ_1', models.CharField(blank=True, choices=[('20/15/10', '20/15/10')], max_length=20, null=True, verbose_name='O5-Bilimsel / Sanatsal toplantı düzenleme kurul başkanlığı / editörlüğü / kurul üyeliğ-1')),
                ('kategori_O6-Q1 ve Q2 kategorisindeki dergilerde editör / editör yardımcılığı / editör kurulu üyeliği (x yıl) _1', models.CharField(blank=True, choices=[('20/15/12', '20/15/12')], max_length=20, null=True, verbose_name='O6-Q1 ve Q2 kategorisindeki dergilerde editör / editör yardımcılığı / editör kurulu üyeliği (x yıl) -1')),
                ('kategori_O6-Q1 ve Q2 kategorisindeki dergilerde editör / editör yardımcılığı / editör kurulu üyeliği (x yıl) _2', models.CharField(blank=True, choices=[('15/10/8', '15/10/8')], max_length=20, null=True, verbose_name='O6-Q1 ve Q2 kategorisindeki dergilerde editör / editör yardımcılığı / editör kurulu üyeliği (x yıl) -2')),
                ('kategori_O6-Q1 ve Q2 kategorisindeki dergilerde editör / editör yardımcılığı / editör kurulu üyeliği (x yıl) _3', models.CharField(blank=True, choices=[('6/4/3', '6/4/3')], max_length=20, null=True, verbose_name='O6-Q1 ve Q2 kategorisindeki dergilerde editör / editör yardımcılığı / editör kurulu üyeliği (x yıl) -3')),
                ('kategori_O7-(ULUSAL)_1', models.CharField(blank=True, choices=[('2', '2')], max_length=20, null=True, verbose_name='O7-(ULUSAL)-1')),
                ('kategori_O7-(ULUSAL)_2', models.CharField(blank=True, choices=[('2', '2')], max_length=20, null=True, verbose_name='O7-(ULUSAL)-2')),
                ('kategori_O7-(ULUSAL)_3', models.CharField(blank=True, choices=[('5/3/2', '5/3/2')], max_length=20, null=True, verbose_name='O7-(ULUSAL)-3')),
                ('kategori_O7-(ULUSAL)_4', models.CharField(blank=True, choices=[('1', '1')], max_length=20, null=True, verbose_name='O7-(ULUSAL)-4')),
                ('kategori_O8-Yayın kurulu üyelikleri (x yıl) _1', models.CharField(blank=True, choices=[('1', '1')], max_length=20, null=True, verbose_name='O8-Yayın kurulu üyelikleri (x yıl) -1')),
                ('kategori_O9-Bilim / Sanat kurulu başkanlığı / üyeliği (x yıl) _1', models.CharField(blank=True, choices=[('2/1', '2/1')], max_length=20, null=True, verbose_name='O9-Bilim / Sanat kurulu başkanlığı / üyeliği (x yıl) -1')),
                ('kategori_O10-Ulusal bir standartın hazırlanmasında görev almak_1', models.CharField(blank=True, choices=[('15', '15')], max_length=20, null=True, verbose_name='O10-Ulusal bir standartın hazırlanmasında görev almak-1')),
                ('kategori_O11-Bilimsel-Sanatsal toplantı düzenleme kurul başkanlığı / editörlüğü / kurul üyeliği_1', models.CharField(blank=True, choices=[('10/8/5', '10/8/5')], max_length=20, null=True, verbose_name='O11-Bilimsel-Sanatsal toplantı düzenleme kurul başkanlığı / editörlüğü / kurul üyeliği-1')),
                ('kategori_O12-Dergilerde editörlük / editör yardımcılığı / editör kurul üyeliği (x yıl)_1', models.CharField(blank=True, choices=[('5/4/3', '5/4/3')], max_length=20, null=True, verbose_name='O12-Dergilerde editörlük / editör yardımcılığı / editör kurul üyeliği (x yıl)-1')),
            ],
        ),
    ]
