# Generated by Django 4.1.7 on 2023-07-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_B1_1', models.CharField(blank=True, choices=[('13/15', '13/15')], max_length=20, null=True, verbose_name='B1-1')),
                ('kategori_B1_2', models.CharField(blank=True, choices=[('5', '5')], max_length=20, null=True, verbose_name='B1-2')),
                ('kategori_B2_1', models.CharField(blank=True, choices=[('6', '6')], max_length=20, null=True, verbose_name='B2-1')),
                ('kategori_B2_2', models.CharField(blank=True, choices=[('3', '3')], max_length=20, null=True, verbose_name='B2-2')),
                ('kategori_C1_1', models.CharField(blank=True, choices=[('100', '100')], max_length=20, null=True, verbose_name='C1-1')),
                ('kategori_C2_1', models.CharField(blank=True, choices=[('30', '30')], max_length=20, null=True, verbose_name='C2-1')),
                ('kategori_C2_2', models.CharField(blank=True, choices=[('5', '5')], max_length=20, null=True, verbose_name='C2-2')),
                ('kategori_C3_1', models.CharField(blank=True, choices=[('50', '50')], max_length=20, null=True, verbose_name='C3-1')),
                ('kategori_C4_1', models.CharField(blank=True, choices=[('40', '40')], max_length=20, null=True, verbose_name='C4-1')),
                ('kategori_C4_2', models.CharField(blank=True, choices=[('30', '30')], max_length=20, null=True, verbose_name='C4-2')),
                ('kategori_C4_3', models.CharField(blank=True, choices=[('10', '10')], max_length=20, null=True, verbose_name='C4-3')),
                ('kategori_D1_1', models.CharField(blank=True, choices=[('18', '18')], max_length=20, null=True, verbose_name='D1-1')),
                ('kategori_D1_2', models.CharField(blank=True, choices=[('8', '8')], max_length=20, null=True, verbose_name='D1-2')),
                ('kategori_D2_1', models.CharField(blank=True, choices=[('10', '10')], max_length=20, null=True, verbose_name='D2-1')),
                ('kategori_D2_2', models.CharField(blank=True, choices=[('5', '5')], max_length=20, null=True, verbose_name='D2-2')),
                ('kategori_D3_1', models.CharField(blank=True, choices=[('4', '4')], max_length=20, null=True, verbose_name='D3-1')),
                ('kategori_D4_1', models.CharField(blank=True, choices=[('8', '8')], max_length=20, null=True, verbose_name='D4-1')),
            ],
        ),
    ]
