# Generated by Django 4.1.7 on 2023-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_alter_profesor_ayok_alter_profesor_onay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='AYOK',
        ),
        migrations.AddField(
            model_name='profesor',
            name='AYOK2',
            field=models.FileField(blank=True, null=True, upload_to='AYOK2/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='onay',
            field=models.FileField(blank=True, null=True, upload_to='onay2/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tez',
            field=models.FileField(blank=True, null=True, upload_to='tezler2/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='yds',
            field=models.FileField(blank=True, null=True, upload_to='yd_belge1/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='özgeçmiş',
            field=models.FileField(blank=True, null=True, upload_to='CV2/'),
        ),
    ]
