# Generated by Django 4.1.7 on 2023-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0004_remove_profesor_ayok_profesor_ayok2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='AYOK2',
            field=models.FileField(blank=True, null=True, upload_to='profesorAYOK/', verbose_name='AYÖK belgesi'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='onay',
            field=models.FileField(blank=True, null=True, upload_to='profesoronay/', verbose_name='Onay Belgesi'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tez',
            field=models.FileField(blank=True, null=True, upload_to='profesortezler/', verbose_name='Tez'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='yds',
            field=models.FileField(blank=True, null=True, upload_to='profesor_yds_belge/', verbose_name='Yabancı Dil Sınav Sonuç Belgesi'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='özgeçmiş',
            field=models.FileField(blank=True, null=True, upload_to='profesorCV/', verbose_name='Özgeçmiş'),
        ),
    ]
