# Generated by Django 4.1.7 on 2023-06-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondocent', '0003_alter_application_doktora_tezi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='doktora_tezi',
            field=models.FileField(blank=True, null=True, upload_to='tezler1/', verbose_name='Doktora Tezi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='eser1',
            field=models.FileField(blank=True, null=True, upload_to='eserler1/', verbose_name='Başlıca Eser 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='eser2',
            field=models.FileField(blank=True, null=True, upload_to='eserler2/', verbose_name='Başlıca Eser 2'),
        ),
        migrations.AlterField(
            model_name='application',
            name='makale',
            field=models.FileField(blank=True, null=True, upload_to='makaleler1/', verbose_name='Makale'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sözlü',
            field=models.FileField(blank=True, null=True, upload_to='sözlüler1/', verbose_name='Sözlü Sınav'),
        ),
        migrations.AlterField(
            model_name='application',
            name='yds_belge',
            field=models.FileField(blank=True, null=True, upload_to='yds_belgeler1/', verbose_name='YDS sınav sonuç belgesi'),
        ),
    ]
