# Generated by Django 4.1.7 on 2023-07-05 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('eser1', models.FileField(default='', upload_to='eserler1/', verbose_name='1.eser')),
                ('eser_türü1', models.CharField(choices=[('A-1a', 'A-1a'), ('A-1b', 'A-1b'), ('A-2a', 'A-2a'), ('C-1', 'C-1')], default='A1-a', max_length=10, verbose_name='Eser Türü 1')),
                ('eser2', models.FileField(default='', upload_to='eserler2/', verbose_name='2.eser')),
                ('eser_türü2', models.CharField(choices=[('A-1a', 'A-1a'), ('A-1b', 'A-1b'), ('A-2a', 'A-2a'), ('C-1', 'C-1')], default='A1-a', max_length=10, verbose_name='Eser Türü 2')),
                ('makale', models.FileField(default='', upload_to='makaleler1/', verbose_name='Makale')),
                ('makale_türü', models.CharField(choices=[('B-1', 'B-1'), ('B-2', 'B-2'), ('D-1', 'D-1'), ('D-2', 'D-2'), ('E-1', 'E-1'), ('K', 'K'), ('L', 'L'), ('M', 'M')], default='B-1', max_length=10, verbose_name='Makale Türü')),
                ('doktora_tezi', models.FileField(default='', upload_to='tezler1/', verbose_name='tez')),
                ('tez_türü', models.CharField(choices=[('B-1', 'B-1'), ('B-2', 'B-2'), ('D-1', 'D-1'), ('D-2', 'D-2'), ('E-1', 'E-1'), ('K', 'K'), ('L', 'L'), ('M', 'M')], default='B-1', max_length=10, verbose_name='Tez Türü')),
                ('yds_belge', models.FileField(default='', upload_to='yds_belgeler1/', verbose_name='YDS Sonuç Belgesi')),
                ('sözlü', models.FileField(default='', upload_to='sözlüler1/', verbose_name='Sözlü Sınav Sonuç Belgesi')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yükleme Tarihi')),
            ],
        ),
    ]
