# Generated by Django 4.1.7 on 2023-05-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('eser', models.FileField(default='default_eser.pdf', upload_to='eserler/', verbose_name='Başlıca Eser')),
                ('eser_türü', models.CharField(choices=[('A-1a', 'A-1a'), ('A-1b', 'A-1b'), ('A-2a', 'A-2a'), ('C-1', 'C-1')], default='A1-a', max_length=10, verbose_name='Eser Türü')),
                ('makale', models.FileField(default='default_makale.pdf', upload_to='makaleler/', verbose_name='Makale')),
                ('makale_türü', models.CharField(choices=[('B-1', 'B-1'), ('B-2', 'B-2'), ('D-1', 'D-1'), ('D-2', 'D-2'), ('E-1', 'E-1'), ('K', 'K'), ('L', 'L'), ('M', 'M')], default='B-1', max_length=10, verbose_name='Makale Türü')),
                ('doktora_tezi', models.FileField(default='default_makale_tezi', upload_to='tezler/', verbose_name='Doktora Tezi')),
                ('tez_türü', models.CharField(choices=[('B-1', 'B-1'), ('B-2', 'B-2'), ('D-1', 'D-1'), ('D-2', 'D-2'), ('E-1', 'E-1'), ('K', 'K'), ('L', 'L'), ('M', 'M')], max_length=10, verbose_name='Tez Türü')),
                ('yds_belge', models.FileField(upload_to='yds_belgeler/', verbose_name='YDS sınav sonuç belgesi')),
            ],
        ),
    ]
