# Generated by Django 4.1.7 on 2023-06-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onyard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='doktora_tezi',
            field=models.FileField(default='default_makale_tezi.pdf', upload_to='tezler/', verbose_name='Doktora Tezi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='yds_belge',
            field=models.FileField(default='default_yds.pdf', upload_to='yds_belgeler/', verbose_name='YDS sınav sonuç belgesi'),
        ),
    ]
