# Generated by Django 4.1.7 on 2023-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onyard', '0003_alter_application_doktora_tezi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tez_türü',
            field=models.CharField(choices=[('B-1', 'B-1'), ('B-2', 'B-2'), ('D-1', 'D-1'), ('D-2', 'D-2'), ('E-1', 'E-1'), ('K', 'K'), ('L', 'L'), ('M', 'M')], default='B-1', max_length=10, verbose_name='Tez Türü'),
        ),
    ]
