# Generated by Django 4.1.7 on 2023-07-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='aciklama',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bastarih',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bittar',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
    ]
