# Generated by Django 4.1.7 on 2023-07-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_aciklama_alter_event_bastarih_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='düzenleyen',
            field=models.TextField(default='', verbose_name='Düzenleyen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ad',
            field=models.CharField(choices=[('DOKTOR ÖĞRETİM ÜYESİ ÖN BAŞVURU TARİHLERİ', 'DOKTOR ÖĞRETİM ÜYESİ ÖN BAŞVURU TARİHLERİ'), ('DOÇENTLİK ÖN BAŞVURU TARİHLERİ', 'DOÇENTLİK ÖN BAŞVURU TARİHLERİ'), ('PROFESÖRLÜK ÖN BAŞVURU TARİHLERİ', 'PROFESÖRLÜK ÖN BAŞVURU TARİHLERİ'), ('DOKTOR ÖĞRETİM ÜYESİ BAŞVURU TARİHLERİ', 'DOKTOR ÖĞRETİM ÜYESİ BAŞVURU TARİHLERİ'), ('DOÇENTLİK BAŞVURU TARİHLERİ', 'DOÇENTLİK BAŞVURU TARİHLERİ'), ('PROFESÖRLÜK BAŞVURU TARİHLERİ', 'PROFESÖRLÜK BAŞVURU TARİHLERİ')], default='DOKTOR ÖĞRETİM ÜYESİ ÖN BAŞVURU', max_length=100),
        ),
    ]
