# Generated by Django 4.1.7 on 2023-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onprof', '0002_remove_application_eser_remove_application_eser_türü_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='eser1',
            field=models.FileField(default='default_eser.pdf', upload_to='eserler/', verbose_name='Başlıca Eser 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='eser3',
            field=models.FileField(default='defaut_eser3.pdf', upload_to='eserler3/', verbose_name='Başlıca Eser 3'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sözlü',
            field=models.FileField(default='default_sözlü.pdf', upload_to='sözlüler/', verbose_name='Sözlü Sınav'),
        ),
        migrations.AlterField(
            model_name='application',
            name='yds_belge',
            field=models.FileField(default='default_yds.pdf', upload_to='yds_belgeler/', verbose_name='YDS sınav sonuç belgesi'),
        ),
    ]
