# Generated by Django 4.1.7 on 2023-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onprof', '0003_alter_application_eser1_alter_application_eser3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='doktora_tezi',
            field=models.FileField(blank=True, null=True, upload_to='tezler/', verbose_name='Doktora Tezi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='eser1',
            field=models.FileField(blank=True, null=True, upload_to='eserler/', verbose_name='Başlıca Eser 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='eser2',
            field=models.FileField(blank=True, null=True, upload_to='eserler2/', verbose_name='Başlıca Eser 2'),
        ),
        migrations.AlterField(
            model_name='application',
            name='eser3',
            field=models.FileField(blank=True, null=True, upload_to='eserler3/', verbose_name='Başlıca Eser 3'),
        ),
        migrations.AlterField(
            model_name='application',
            name='makale',
            field=models.FileField(blank=True, null=True, upload_to='makaleler/', verbose_name='Makale'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sözlü',
            field=models.FileField(blank=True, null=True, upload_to='sözlüler/', verbose_name='Sözlü Sınav'),
        ),
        migrations.AlterField(
            model_name='application',
            name='yds_belge',
            field=models.FileField(blank=True, null=True, upload_to='yds_belgeler/', verbose_name='YDS sınav sonuç belgesi'),
        ),
    ]
