# Generated by Django 4.1.7 on 2023-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardimci', '0003_alter_yardimci_ayok_alter_yardimci_onay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardimci',
            name='yds',
            field=models.FileField(blank=True, null=True, upload_to='yd_belge/', verbose_name='Yabancı Dil Sınav Sonuç Belgesi'),
        ),
        migrations.AlterField(
            model_name='yardimci',
            name='özgeçmiş',
            field=models.FileField(blank=True, null=True, upload_to='CV/', verbose_name='Özgeçmiş'),
        ),
    ]
