# Generated by Django 4.1.7 on 2023-07-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfile', '0002_docent_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docent',
            name='form7',
            field=models.FileField(default='', upload_to='docentform7/', verbose_name='FORM-7'),
        ),
    ]
