# Generated by Django 4.1.7 on 2023-07-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfile', '0003_alter_docent_form7'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docent',
            old_name='özgeçmiş',
            new_name='ozgecmis',
        ),
    ]
